name: lockity_flutter
description: "Lockity"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  http: ^1.1.0
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.1.0
  webview_flutter: ^4.4.4
  mqtt_client: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/icons/